"""ssh into a session's agent container, and session names (so `ssh <name>` works).

There is no listening port: the generated ssh config uses
    ProxyCommand docker exec -i air-agent-<id> /usr/sbin/sshd -i -f /home/agent/.sshd/sshd_config
so sshd runs per connection, unprivileged, as the container's own user, and only someone who can run docker on this
machine can reach it. Authentication is a controller-wide key (~/.airlock/ssh/id_ed25519) installed in each session.
"""
from __future__ import annotations

import os
import re
import shlex
import subprocess
from pathlib import Path

from .config import HOME, ConfigError

KEY = HOME / "ssh" / "id_ed25519"
CONFIG = HOME / "ssh_config"
USER = "agent"
SSHD_DIR = "/home/agent/.sshd"
NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]{0,62}$")
ID_RE = re.compile(r"^[a-f0-9]{6,32}$")

SSHD_CONFIG = f"""HostKey {SSHD_DIR}/host_ed25519
AuthorizedKeysFile {SSHD_DIR}/authorized_keys
PidFile none
UsePAM no
PasswordAuthentication no
KbdInteractiveAuthentication no
StrictModes no
PermitUserEnvironment no
PrintMotd no
LogLevel ERROR
Subsystem sftp internal-sftp
"""

# A login shell does not inherit the container's environment. Re-read the allowed names from PID 1 at login, so nothing
# secret (MCP_TOKEN) is written to a file.
PROFILE = r"""
if [ -r /proc/1/environ ]; then
  while IFS= read -r -d '' kv; do
    case "$kv" in
      HTTP_PROXY=*|HTTPS_PROXY=*|http_proxy=*|https_proxy=*|NO_PROXY=*|MCP_URL=*|MCP_TOKEN=*|CLAUDE_CODE_*|AIRLOCK_*) export "$kv";;
    esac
  done < /proc/1/environ
fi
export CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN=1   # `claude` started over ssh uses the classic renderer too
# Shells start in /src, but a gateway session's MCP server and instructions live in /workspace. Without them `claude` has no
# tools and falls back to bash, so load them explicitly whatever the current directory is. Bypass mode as in attach and
# the UI: the container is the boundary, not permission prompts.
if [ -f /workspace/.mcp.json ]; then
  claude() { command claude --dangerously-skip-permissions --mcp-config /workspace/.mcp.json --append-system-prompt "$(cat /workspace/AIRLOCK_ENV.md 2>/dev/null)" "$@"; }
elif [ -f /workspace/AIRLOCK_NODES.md ]; then   # sandbox session: the node list and how to reach them
  claude() { command claude --dangerously-skip-permissions --append-system-prompt "$(cat /workspace/AIRLOCK_NODES.md)" "$@"; }
else
  claude() { command claude --dangerously-skip-permissions "$@"; }
fi
cd /src 2>/dev/null || cd /workspace 2>/dev/null   # shells start in the mounted source folders
"""


def ensure_client_key() -> Path:
    """The controller's ssh key for container logins. A missing, unreadable or loose-permission key is replaced
    (it is only a convenience key: docker access is the real gate), and the private part is always mode 0600."""
    pub = KEY.with_suffix(".pub")
    if KEY.exists() and pub.exists():
        KEY.chmod(0o600)
        ok = subprocess.run(["ssh-keygen", "-y", "-f", str(KEY)], capture_output=True, text=True)
        if ok.returncode == 0 and ok.stdout.split()[:1] == ["ssh-ed25519"]:
            return KEY
    KEY.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    KEY.unlink(missing_ok=True)
    pub.unlink(missing_ok=True)
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "airlock-controller", "-f", str(KEY)], check=True)
    KEY.chmod(0o600)
    return KEY


def setup_container(sid: str) -> None:
    """Install sshd config, host key and authorized key inside the running agent container. Raises on failure."""
    pub = (ensure_client_key().with_suffix(".pub")).read_text().strip()
    script = (f"set -e; d={SSHD_DIR}; mkdir -p $d && chmod 700 $d; "
              f"[ -f $d/host_ed25519 ] || ssh-keygen -q -t ed25519 -N '' -f $d/host_ed25519; "
              f"cat > $d/authorized_keys; chmod 600 $d/authorized_keys; "
              f"printf %s {shlex.quote(SSHD_CONFIG)} > $d/sshd_config; "
              f"printf %s {shlex.quote(PROFILE)} > /home/agent/.bash_profile; cp /home/agent/.bash_profile /home/agent/.bashrc")
    p = subprocess.run(["docker", "exec", "-i", f"air-agent-{sid}", "sh", "-c", script], input=pub + "\n", capture_output=True, text=True)
    if p.returncode:
        raise RuntimeError(f"ssh setup failed: {p.stderr.strip()[-200:]}")
    from .session import apply_claude_settings   # also repairs running sessions: `airlock ssh setup`
    apply_claude_settings(f"air-agent-{sid}")


def sessions_with_ssh(sessions: list[dict]) -> list[dict]:
    return [s for s in sessions if s.get("ssh") and s.get("status") == "running"]


def render_config(sessions: list[dict]) -> str:
    out = ["# Generated by AirlockAI: do not edit. Use it with `ssh -F ~/.airlock/ssh_config NAME` or run `airlock ssh setup` once.\n"]
    for s in sessions_with_ssh(sessions):
        aliases = [s["id"]] + ([s["name"]] if s.get("name") else [])
        out.append(f"Host {' '.join(aliases)}\n  HostName {s['id']}\n  User {USER}\n  IdentityFile {KEY}\n  IdentitiesOnly yes\n"
                   f"  ProxyCommand docker exec -i air-agent-{s['id']} /usr/sbin/sshd -i -f {SSHD_DIR}/sshd_config\n"
                   f"  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  LogLevel ERROR\n  ServerAliveInterval 30\n")
    return "\n".join(out)


def write_config(sessions: list[dict] | None = None) -> Path:
    from .session import list_sessions
    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    tmp = CONFIG.with_suffix(".tmp")
    tmp.write_text(render_config(list_sessions() if sessions is None else sessions))
    os.replace(tmp, CONFIG)
    return CONFIG


USER_SSH_CONFIG = Path.home() / ".ssh" / "config"


def include_line() -> str:
    return f"Include {CONFIG}"


def include_active() -> bool:
    try:
        return any(ln.strip() in (include_line(), "Include ~/.airlock/ssh_config") for ln in USER_SSH_CONFIG.read_text().splitlines())
    except OSError:
        return False


def setup_include() -> str:
    """Add the Include line at the top of ~/.ssh/config (Include must come before any Host/Match). Idempotent."""
    if include_active():
        return "already set up"
    USER_SSH_CONFIG.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    old = USER_SSH_CONFIG.read_text() if USER_SSH_CONFIG.exists() else ""
    USER_SSH_CONFIG.write_text(f"{include_line()}\n\n{old}")
    USER_SSH_CONFIG.chmod(0o600)
    return f"added `{include_line()}` to {USER_SSH_CONFIG}"


def target(s: dict) -> str:
    return s.get("name") or s["id"]


def command(s: dict) -> str:
    """The command to paste: short form once the Include is in place, else with -F."""
    return f"ssh {target(s)}" if include_active() else f"ssh -F {CONFIG} {target(s)}"


def refresh_sessions() -> list[str]:
    """Re-install the controller key and sshd config in every running session that has ssh. Returns status lines."""
    from .session import list_sessions
    out = []
    ensure_client_key()
    for s in sessions_with_ssh(list_sessions()):
        try:
            setup_container(s["id"])
            out.append(f"session {s['id']}: ssh access refreshed")
        except Exception as e:
            out.append(f"session {s['id']}: {e}")
    write_config()
    return out


def provision(sid: str) -> bool:
    """Called after a session's agent container is up. Best effort: failure only means there is no ssh command."""
    try:
        setup_container(sid)
        return True
    except Exception:
        return False


def check_name(name: str, sid: str, sessions: list[dict]) -> str:
    name = name.strip()
    if not name:
        return ""
    if not NAME_RE.match(name):
        raise ConfigError("a session name starts with a letter and uses letters, digits, . _ - (max 63): it becomes the ssh host name")
    if ID_RE.match(name):
        raise ConfigError("that name looks like a session id; pick another")
    for s in sessions:
        if s["id"] != sid and (s.get("name") == name or s["id"] == name):
            raise ConfigError(f"the name {name} is already used by session {s['id']}")
    return name


def set_name(sid: str, name: str) -> str:
    from .audit import Audit
    from .session import list_sessions, load_state, save_state
    st = load_state(sid)
    name = check_name(name, sid, list_sessions())
    if name:
        st["name"] = name
    else:
        st.pop("name", None)
    save_state(st)
    write_config()
    Audit(sid).log("controller", "session.renamed", name=name)
    return name
